### ISSUE TITLE
error in clarity-native-bin's postInstallScript while running in windows operating system

### ISSUE THREAD

**Issue by nervehammer** [blockstack/clarity-js-sdk#35]
**OS:** Windows 10 Pro 1903
**Node version:** 10.16.0
**Npm version:** 6.9.0

**logs below:**

```
C:\Users\springrole\Desktop\clarity-js-sdk>npm install

> clarity-monorepo-wrapper@0.0.0 prepare C:\Users\springrole\Desktop\clarity-js-sdk
> lerna bootstrap

lerna notice cli v3.14.1
lerna info Bootstrapping 6 packages
lerna info Symlinking packages and binaries
lerna info lifecycle @blockstack/clarity-native-bin@0.1.9-alpha.0~postinstall: @blockstack/clarity-native-bin@0.1.9-alpha.0

> @blockstack/clarity-native-bin@0.1.9-alpha.0 postinstall C:\Users\springrole\Desktop\clarity-js-sdk\packages\clarity-native-bin
> node postInstallScript.js

Running: npx ts-node@^8.2.0 --project C:\Users\springrole\Desktop\clarity-js-sdk\packages\clarity-native-bin\tsconfig.build.json C:\Users\springrole\Desktop\clarity-js-sdk\packages\clarity-native-bin\src\directInstall.ts
child_process.js:650
    throw err;
    ^

Error: spawnSync npx ENOENT
    at Object.spawnSync (internal/child_process.js:1002:20)
    at spawnSync (child_process.js:614:24)
    at Object.execFileSync (child_process.js:642:13)
    at tsNodeInstall (C:\Users\springrole\Desktop\clarity-js-sdk\packages\clarity-native-bin\postInstallScript.js:57:16)
    at Object.<anonymous> (C:\Users\springrole\Desktop\clarity-js-sdk\packages\clarity-native-bin\postInstallScript.js:19:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
lerna info lifecycle @blockstack/clarity-native-bin@0.1.9-alpha.0~postinstall: Failed to exec postinstall script
lerna ERR! lifecycle "postinstall" errored in "@blockstack/clarity-native-bin", exiting 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! clarity-monorepo-wrapper@0.0.0 prepare: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the clarity-monorepo-wrapper@0.0.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\springrole\AppData\Roaming\npm-cache\_logs\2019-07-01T12_41_37_537Z-debug.log
```

**Comment by nervehammer** [comment]
@zone117x this should be fixed entirely after fix/windows-unit-test branch merges to master
