### ISSUE TITLE
SDK cares about line breaks

### ISSUE THREAD

**Issue by xmakina** [blockstack/clarity-js-sdk#70]
Initialise the clarity-hello-world project
Open hello-world.clar
Change line ending from LF to CRLF (this can be done in Visual Studio Code)
Save hello-world.clar
Run tests

Expected:
Tests pass

Actual:

```
ExecutionError: Launch contract failed with bad exit code 1: Failed to parse program.
Caused by: ASTError(ParseError { err: FailedParsingRemainder("\r\n   (ok \"hello world\"))\r\n\r\n(define-public (echo-number (val int))\r\n   (ok val))\r\n"), pre_expressions: None, diagnostic: Diagnostic { level: Error, message: "Failed to lex input remainder: \'\r\n   (ok \"hello world\"))\r\n\r\n(define-public (echo-number (val int))\r\n   (ok val))\r\n\'", spans: [], suggestion: None } })
      at NativeClarityBinProvider.launchContract (node_modules\@blockstack\clarity\src\providers\clarityBin\index.ts:126:13)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by zone117x** [comment]
The Clarity spec was updated to no longer allow CRLF. The contract deployment code needs updated to normalize the line endings.
